version: '3'
services:
  conjur-server:
    image: registry.tld/conjur-appliance:5.0-stable
    environment:
      CONJUR_AUTHENTICATORS: authn-jwt/circleci1
    security_opt:
      - seccomp:unconfined # --security-opt seccomp=unconfined
    hostname: conjur
    ports:
      - "443"
