version: 2.1

orbs:
  conjur-circleci: cyberark/conjur-circleci@1.0.0

jobs:
  test-conjur:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - conjur-circleci/retrieve_secret:
          url: "https://conjur_appliance_url"
          account: "myaccount"
          service_id: "circleci"
          secrets: "secret2|sql_username;secret1;"
      - run:
          name: Show secrets
          command: |
            echo "Secret1: $SECRET1"
            echo "SQL Username: $SQL_USERNAME"

workflows:
  use-my-orb:
    jobs:
      - test-conjur
