# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/reference/configuration-reference
version: 2.1

orbs:
  conjur-circleci: cyberark/conjur-circleci-orb@0.0.1

jobs:
  say-hello:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: "echo Hello, World!"
          
workflows:
  use-my-orb:
    jobs:
      - conjur-circleci/retrieve_secret:
          account: myaccount
          secrets: secret2|sql_username;secret1;
          service_id: circleci
          url: https://conjur_appliance_url
